### ISSUE TITLE
NodeJS CLI

### ISSUE THREAD

**Issue by osmarpetry** [osmarpetry/tokens-figma-node#3]
## Today to use this code you should do:

1. Copy a `figmaApiKey` and `figmaFileID` to `index.js`
2. Run `node index.js`
3. Then run `node json-to-css.js`
4. Copy the CSS files from `/output` to your project

## What I expect:

1. Call a CLI to insert the `figmaApiKey` and `figmaFileID` 
2. Chose the folder to output the CSS variables

## What more?

To do the second step of `What I expect` you should insert the relative directory name on `json-to-css.js` file

**Comment by redice44** [comment]
I'll give this a shot 👍
