### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by osmarpetry** [osmarpetry/tokens-figma-node#4]
## Why this issue?
Today the code is a mess. Because I did it just to solve one problem for me, and it was the first time I was creating a parser.

## How to do it?
The `index.js` just pull the code from Figma to a `Object`. In the end of this file, it push the object to a `JSON` file.

The `json-to-css.js` get this previous `JSON`file and parse to multiples `CSS` files.

**Comment by pupupulp** [comment]
Hi @osmarpetry ,

I would kindly like to give this one a try, you can assign it to me if it is alright with you :D :D :D

**Comment by osmarpetry** [comment]
@pupupulp of course, just let me review the pull request that will include a CLI. 

After it, you can easily refactor the code, but you can start it now if want, but you will have some code conflicts to solve.

If you need any help to understand the code, just call me here. If it necessary, we can chat.

**Comment by osmarpetry** [comment]
Pull request is merged, you're free to go now! 

Check the new way to use the code from PR #5

**Comment by pupupulp** [comment]
I'll get started with this one now :D

**Comment by pupupulp** [comment]
Hi @osmarpetry ,

I've made a pull request for this one #7, I hope this helps for this issue :D :D :D

**Comment by osmarpetry** [comment]
Issue closed from PR #7
